package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiningRoomAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiningRoomAllPropertiesEquals(DiningRoom expected, DiningRoom actual) {
        assertDiningRoomAutoGeneratedPropertiesEquals(expected, actual);
        assertDiningRoomAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiningRoomAllUpdatablePropertiesEquals(DiningRoom expected, DiningRoom actual) {
        assertDiningRoomUpdatableFieldsEquals(expected, actual);
        assertDiningRoomUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiningRoomAutoGeneratedPropertiesEquals(DiningRoom expected, DiningRoom actual) {
        assertThat(actual)
            .as("Verify DiningRoom auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiningRoomUpdatableFieldsEquals(DiningRoom expected, DiningRoom actual) {
        assertThat(actual)
            .as("Verify DiningRoom relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getFloor()).as("check floor").isEqualTo(expected.getFloor()))
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getFloorPlanUrl()).as("check floorPlanUrl").isEqualTo(expected.getFloorPlanUrl()))
            .satisfies(a -> assertThat(a.getWidthPx()).as("check widthPx").isEqualTo(expected.getWidthPx()))
            .satisfies(a -> assertThat(a.getHeightPx()).as("check heightPx").isEqualTo(expected.getHeightPx()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiningRoomUpdatableRelationshipsEquals(DiningRoom expected, DiningRoom actual) {
        assertThat(actual)
            .as("Verify DiningRoom relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
