package md.utm.restaurant.domain;

import static md.utm.restaurant.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LocationMenuItemOverrideAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationMenuItemOverrideAllPropertiesEquals(
        LocationMenuItemOverride expected,
        LocationMenuItemOverride actual
    ) {
        assertLocationMenuItemOverrideAutoGeneratedPropertiesEquals(expected, actual);
        assertLocationMenuItemOverrideAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationMenuItemOverrideAllUpdatablePropertiesEquals(
        LocationMenuItemOverride expected,
        LocationMenuItemOverride actual
    ) {
        assertLocationMenuItemOverrideUpdatableFieldsEquals(expected, actual);
        assertLocationMenuItemOverrideUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationMenuItemOverrideAutoGeneratedPropertiesEquals(
        LocationMenuItemOverride expected,
        LocationMenuItemOverride actual
    ) {
        assertThat(actual)
            .as("Verify LocationMenuItemOverride auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationMenuItemOverrideUpdatableFieldsEquals(
        LocationMenuItemOverride expected,
        LocationMenuItemOverride actual
    ) {
        assertThat(actual)
            .as("Verify LocationMenuItemOverride relevant properties")
            .satisfies(a ->
                assertThat(a.getIsAvailableAtLocation()).as("check isAvailableAtLocation").isEqualTo(expected.getIsAvailableAtLocation())
            )
            .satisfies(a ->
                assertThat(a.getPriceOverride())
                    .as("check priceOverride")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPriceOverride())
            )
            .satisfies(a ->
                assertThat(a.getPreparationTimeOverride())
                    .as("check preparationTimeOverride")
                    .isEqualTo(expected.getPreparationTimeOverride())
            )
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationMenuItemOverrideUpdatableRelationshipsEquals(
        LocationMenuItemOverride expected,
        LocationMenuItemOverride actual
    ) {
        assertThat(actual)
            .as("Verify LocationMenuItemOverride relationships")
            .satisfies(a -> assertThat(a.getMenuItem()).as("check menuItem").isEqualTo(expected.getMenuItem()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
