package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocationHoursAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationHoursAllPropertiesEquals(LocationHours expected, LocationHours actual) {
        assertLocationHoursAutoGeneratedPropertiesEquals(expected, actual);
        assertLocationHoursAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationHoursAllUpdatablePropertiesEquals(LocationHours expected, LocationHours actual) {
        assertLocationHoursUpdatableFieldsEquals(expected, actual);
        assertLocationHoursUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationHoursAutoGeneratedPropertiesEquals(LocationHours expected, LocationHours actual) {
        assertThat(actual)
            .as("Verify LocationHours auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationHoursUpdatableFieldsEquals(LocationHours expected, LocationHours actual) {
        assertThat(actual)
            .as("Verify LocationHours relevant properties")
            .satisfies(a -> assertThat(a.getDayOfWeek()).as("check dayOfWeek").isEqualTo(expected.getDayOfWeek()))
            .satisfies(a -> assertThat(a.getOpenTime()).as("check openTime").isEqualTo(expected.getOpenTime()))
            .satisfies(a -> assertThat(a.getCloseTime()).as("check closeTime").isEqualTo(expected.getCloseTime()))
            .satisfies(a -> assertThat(a.getIsClosed()).as("check isClosed").isEqualTo(expected.getIsClosed()))
            .satisfies(a -> assertThat(a.getSpecialNote()).as("check specialNote").isEqualTo(expected.getSpecialNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocationHoursUpdatableRelationshipsEquals(LocationHours expected, LocationHours actual) {
        assertThat(actual)
            .as("Verify LocationHours relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
