package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemAllergenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllergenAllPropertiesEquals(MenuItemAllergen expected, MenuItemAllergen actual) {
        assertMenuItemAllergenAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemAllergenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllergenAllUpdatablePropertiesEquals(MenuItemAllergen expected, MenuItemAllergen actual) {
        assertMenuItemAllergenUpdatableFieldsEquals(expected, actual);
        assertMenuItemAllergenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllergenAutoGeneratedPropertiesEquals(MenuItemAllergen expected, MenuItemAllergen actual) {
        assertThat(actual)
            .as("Verify MenuItemAllergen auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllergenUpdatableFieldsEquals(MenuItemAllergen expected, MenuItemAllergen actual) {
        assertThat(actual)
            .as("Verify MenuItemAllergen relevant properties")
            .satisfies(a -> assertThat(a.getAllergen()).as("check allergen").isEqualTo(expected.getAllergen()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllergenUpdatableRelationshipsEquals(MenuItemAllergen expected, MenuItemAllergen actual) {
        assertThat(actual)
            .as("Verify MenuItemAllergen relationships")
            .satisfies(a -> assertThat(a.getMenuItem()).as("check menuItem").isEqualTo(expected.getMenuItem()));
    }
}
