package md.utm.restaurant.domain;

import static md.utm.restaurant.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllUpdatablePropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemUpdatableFieldsEquals(expected, actual);
        assertMenuItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAutoGeneratedPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertThat(actual)
            .as("Verify MenuItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableFieldsEquals(MenuItem expected, MenuItem actual) {
        assertThat(actual)
            .as("Verify MenuItem relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a ->
                assertThat(a.getDiscountedPrice())
                    .as("check discountedPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountedPrice())
            )
            .satisfies(a ->
                assertThat(a.getPreparationTimeMinutes()).as("check preparationTimeMinutes").isEqualTo(expected.getPreparationTimeMinutes())
            )
            .satisfies(a -> assertThat(a.getCalories()).as("check calories").isEqualTo(expected.getCalories()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getIsAvailable()).as("check isAvailable").isEqualTo(expected.getIsAvailable()))
            .satisfies(a -> assertThat(a.getIsFeatured()).as("check isFeatured").isEqualTo(expected.getIsFeatured()))
            .satisfies(a -> assertThat(a.getIsVegetarian()).as("check isVegetarian").isEqualTo(expected.getIsVegetarian()))
            .satisfies(a -> assertThat(a.getIsVegan()).as("check isVegan").isEqualTo(expected.getIsVegan()))
            .satisfies(a -> assertThat(a.getIsGlutenFree()).as("check isGlutenFree").isEqualTo(expected.getIsGlutenFree()))
            .satisfies(a -> assertThat(a.getSpicyLevel()).as("check spicyLevel").isEqualTo(expected.getSpicyLevel()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableRelationshipsEquals(MenuItem expected, MenuItem actual) {
        assertThat(actual)
            .as("Verify MenuItem relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
