package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemOptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionAllPropertiesEquals(MenuItemOption expected, MenuItemOption actual) {
        assertMenuItemOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionAllUpdatablePropertiesEquals(MenuItemOption expected, MenuItemOption actual) {
        assertMenuItemOptionUpdatableFieldsEquals(expected, actual);
        assertMenuItemOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionAutoGeneratedPropertiesEquals(MenuItemOption expected, MenuItemOption actual) {
        assertThat(actual)
            .as("Verify MenuItemOption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionUpdatableFieldsEquals(MenuItemOption expected, MenuItemOption actual) {
        assertThat(actual)
            .as("Verify MenuItemOption relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getIsRequired()).as("check isRequired").isEqualTo(expected.getIsRequired()))
            .satisfies(a -> assertThat(a.getMaxSelections()).as("check maxSelections").isEqualTo(expected.getMaxSelections()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionUpdatableRelationshipsEquals(MenuItemOption expected, MenuItemOption actual) {
        assertThat(actual)
            .as("Verify MenuItemOption relationships")
            .satisfies(a -> assertThat(a.getMenuItem()).as("check menuItem").isEqualTo(expected.getMenuItem()));
    }
}
