package md.utm.restaurant.domain;

import static md.utm.restaurant.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemOptionValueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionValueAllPropertiesEquals(MenuItemOptionValue expected, MenuItemOptionValue actual) {
        assertMenuItemOptionValueAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemOptionValueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionValueAllUpdatablePropertiesEquals(MenuItemOptionValue expected, MenuItemOptionValue actual) {
        assertMenuItemOptionValueUpdatableFieldsEquals(expected, actual);
        assertMenuItemOptionValueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionValueAutoGeneratedPropertiesEquals(MenuItemOptionValue expected, MenuItemOptionValue actual) {
        assertThat(actual)
            .as("Verify MenuItemOptionValue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionValueUpdatableFieldsEquals(MenuItemOptionValue expected, MenuItemOptionValue actual) {
        assertThat(actual)
            .as("Verify MenuItemOptionValue relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a ->
                assertThat(a.getPriceAdjustment())
                    .as("check priceAdjustment")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPriceAdjustment())
            )
            .satisfies(a -> assertThat(a.getIsDefault()).as("check isDefault").isEqualTo(expected.getIsDefault()))
            .satisfies(a -> assertThat(a.getIsAvailable()).as("check isAvailable").isEqualTo(expected.getIsAvailable()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemOptionValueUpdatableRelationshipsEquals(MenuItemOptionValue expected, MenuItemOptionValue actual) {
        assertThat(actual)
            .as("Verify MenuItemOptionValue relationships")
            .satisfies(a -> assertThat(a.getOption()).as("check option").isEqualTo(expected.getOption()));
    }
}
