package md.utm.restaurant.domain;

import static md.utm.restaurant.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrderItemOptionSelectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemOptionSelectionAllPropertiesEquals(
        OrderItemOptionSelection expected,
        OrderItemOptionSelection actual
    ) {
        assertOrderItemOptionSelectionAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderItemOptionSelectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemOptionSelectionAllUpdatablePropertiesEquals(
        OrderItemOptionSelection expected,
        OrderItemOptionSelection actual
    ) {
        assertOrderItemOptionSelectionUpdatableFieldsEquals(expected, actual);
        assertOrderItemOptionSelectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemOptionSelectionAutoGeneratedPropertiesEquals(
        OrderItemOptionSelection expected,
        OrderItemOptionSelection actual
    ) {
        assertThat(actual)
            .as("Verify OrderItemOptionSelection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemOptionSelectionUpdatableFieldsEquals(
        OrderItemOptionSelection expected,
        OrderItemOptionSelection actual
    ) {
        assertThat(actual)
            .as("Verify OrderItemOptionSelection relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderItemOptionSelectionUpdatableRelationshipsEquals(
        OrderItemOptionSelection expected,
        OrderItemOptionSelection actual
    ) {
        assertThat(actual)
            .as("Verify OrderItemOptionSelection relationships")
            .satisfies(a -> assertThat(a.getOptionValue()).as("check optionValue").isEqualTo(expected.getOptionValue()))
            .satisfies(a -> assertThat(a.getOrderItem()).as("check orderItem").isEqualTo(expected.getOrderItem()));
    }
}
