package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReservationTableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationTableAllPropertiesEquals(ReservationTable expected, ReservationTable actual) {
        assertReservationTableAutoGeneratedPropertiesEquals(expected, actual);
        assertReservationTableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationTableAllUpdatablePropertiesEquals(ReservationTable expected, ReservationTable actual) {
        assertReservationTableUpdatableFieldsEquals(expected, actual);
        assertReservationTableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationTableAutoGeneratedPropertiesEquals(ReservationTable expected, ReservationTable actual) {
        assertThat(actual)
            .as("Verify ReservationTable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationTableUpdatableFieldsEquals(ReservationTable expected, ReservationTable actual) {
        assertThat(actual)
            .as("Verify ReservationTable relevant properties")
            .satisfies(a -> assertThat(a.getAssignedAt()).as("check assignedAt").isEqualTo(expected.getAssignedAt()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReservationTableUpdatableRelationshipsEquals(ReservationTable expected, ReservationTable actual) {
        assertThat(actual)
            .as("Verify ReservationTable relationships")
            .satisfies(a -> assertThat(a.getTable()).as("check table").isEqualTo(expected.getTable()))
            .satisfies(a -> assertThat(a.getReservation()).as("check reservation").isEqualTo(expected.getReservation()));
    }
}
