package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RestaurantTableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantTableAllPropertiesEquals(RestaurantTable expected, RestaurantTable actual) {
        assertRestaurantTableAutoGeneratedPropertiesEquals(expected, actual);
        assertRestaurantTableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantTableAllUpdatablePropertiesEquals(RestaurantTable expected, RestaurantTable actual) {
        assertRestaurantTableUpdatableFieldsEquals(expected, actual);
        assertRestaurantTableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantTableAutoGeneratedPropertiesEquals(RestaurantTable expected, RestaurantTable actual) {
        assertThat(actual)
            .as("Verify RestaurantTable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantTableUpdatableFieldsEquals(RestaurantTable expected, RestaurantTable actual) {
        assertThat(actual)
            .as("Verify RestaurantTable relevant properties")
            .satisfies(a -> assertThat(a.getTableNumber()).as("check tableNumber").isEqualTo(expected.getTableNumber()))
            .satisfies(a -> assertThat(a.getShape()).as("check shape").isEqualTo(expected.getShape()))
            .satisfies(a -> assertThat(a.getMinCapacity()).as("check minCapacity").isEqualTo(expected.getMinCapacity()))
            .satisfies(a -> assertThat(a.getMaxCapacity()).as("check maxCapacity").isEqualTo(expected.getMaxCapacity()))
            .satisfies(a -> assertThat(a.getPositionX()).as("check positionX").isEqualTo(expected.getPositionX()))
            .satisfies(a -> assertThat(a.getPositionY()).as("check positionY").isEqualTo(expected.getPositionY()))
            .satisfies(a -> assertThat(a.getWidthPx()).as("check widthPx").isEqualTo(expected.getWidthPx()))
            .satisfies(a -> assertThat(a.getHeightPx()).as("check heightPx").isEqualTo(expected.getHeightPx()))
            .satisfies(a -> assertThat(a.getRotation()).as("check rotation").isEqualTo(expected.getRotation()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantTableUpdatableRelationshipsEquals(RestaurantTable expected, RestaurantTable actual) {
        assertThat(actual)
            .as("Verify RestaurantTable relationships")
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()));
    }
}
