package md.utm.restaurant.domain;

import static md.utm.restaurant.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RestaurantOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantOrderAllPropertiesEquals(RestaurantOrder expected, RestaurantOrder actual) {
        assertRestaurantOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertRestaurantOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantOrderAllUpdatablePropertiesEquals(RestaurantOrder expected, RestaurantOrder actual) {
        assertRestaurantOrderUpdatableFieldsEquals(expected, actual);
        assertRestaurantOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantOrderAutoGeneratedPropertiesEquals(RestaurantOrder expected, RestaurantOrder actual) {
        assertThat(actual)
            .as("Verify RestaurantOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantOrderUpdatableFieldsEquals(RestaurantOrder expected, RestaurantOrder actual) {
        assertThat(actual)
            .as("Verify RestaurantOrder relevant properties")
            .satisfies(a -> assertThat(a.getOrderCode()).as("check orderCode").isEqualTo(expected.getOrderCode()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIsPreOrder()).as("check isPreOrder").isEqualTo(expected.getIsPreOrder()))
            .satisfies(a -> assertThat(a.getScheduledFor()).as("check scheduledFor").isEqualTo(expected.getScheduledFor()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            )
            .satisfies(a ->
                assertThat(a.getTaxAmount()).as("check taxAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTaxAmount())
            )
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            )
            .satisfies(a ->
                assertThat(a.getSpecialInstructions()).as("check specialInstructions").isEqualTo(expected.getSpecialInstructions())
            )
            .satisfies(a -> assertThat(a.getEstimatedReadyTime()).as("check estimatedReadyTime").isEqualTo(expected.getEstimatedReadyTime())
            )
            .satisfies(a -> assertThat(a.getConfirmedAt()).as("check confirmedAt").isEqualTo(expected.getConfirmedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRestaurantOrderUpdatableRelationshipsEquals(RestaurantOrder expected, RestaurantOrder actual) {
        assertThat(actual)
            .as("Verify RestaurantOrder relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getTable()).as("check table").isEqualTo(expected.getTable()))
            .satisfies(a -> assertThat(a.getPromotion()).as("check promotion").isEqualTo(expected.getPromotion()))
            .satisfies(a -> assertThat(a.getReservation()).as("check reservation").isEqualTo(expected.getReservation()));
    }
}
