package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewAllPropertiesEquals(Review expected, Review actual) {
        assertReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewAllUpdatablePropertiesEquals(Review expected, Review actual) {
        assertReviewUpdatableFieldsEquals(expected, actual);
        assertReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewAutoGeneratedPropertiesEquals(Review expected, Review actual) {
        assertThat(actual)
            .as("Verify Review auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewUpdatableFieldsEquals(Review expected, Review actual) {
        assertThat(actual)
            .as("Verify Review relevant properties")
            .satisfies(a -> assertThat(a.getOverallRating()).as("check overallRating").isEqualTo(expected.getOverallRating()))
            .satisfies(a -> assertThat(a.getFoodRating()).as("check foodRating").isEqualTo(expected.getFoodRating()))
            .satisfies(a -> assertThat(a.getServiceRating()).as("check serviceRating").isEqualTo(expected.getServiceRating()))
            .satisfies(a -> assertThat(a.getAmbienceRating()).as("check ambienceRating").isEqualTo(expected.getAmbienceRating()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()))
            .satisfies(a -> assertThat(a.getIsApproved()).as("check isApproved").isEqualTo(expected.getIsApproved()))
            .satisfies(a -> assertThat(a.getIsAnonymous()).as("check isAnonymous").isEqualTo(expected.getIsAnonymous()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReviewUpdatableRelationshipsEquals(Review expected, Review actual) {
        assertThat(actual)
            .as("Verify Review relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getReservation()).as("check reservation").isEqualTo(expected.getReservation()));
    }
}
