package md.utm.restaurant.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WaitingListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitingListAllPropertiesEquals(WaitingList expected, WaitingList actual) {
        assertWaitingListAutoGeneratedPropertiesEquals(expected, actual);
        assertWaitingListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitingListAllUpdatablePropertiesEquals(WaitingList expected, WaitingList actual) {
        assertWaitingListUpdatableFieldsEquals(expected, actual);
        assertWaitingListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitingListAutoGeneratedPropertiesEquals(WaitingList expected, WaitingList actual) {
        assertThat(actual)
            .as("Verify WaitingList auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitingListUpdatableFieldsEquals(WaitingList expected, WaitingList actual) {
        assertThat(actual)
            .as("Verify WaitingList relevant properties")
            .satisfies(a -> assertThat(a.getRequestedDate()).as("check requestedDate").isEqualTo(expected.getRequestedDate()))
            .satisfies(a -> assertThat(a.getRequestedTime()).as("check requestedTime").isEqualTo(expected.getRequestedTime()))
            .satisfies(a -> assertThat(a.getPartySize()).as("check partySize").isEqualTo(expected.getPartySize()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getIsNotified()).as("check isNotified").isEqualTo(expected.getIsNotified()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaitingListUpdatableRelationshipsEquals(WaitingList expected, WaitingList actual) {
        assertThat(actual)
            .as("Verify WaitingList relationships")
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()));
    }
}
